### ISSUE TITLE
Crash when opening the page

### ISSUE THREAD

**Issue by dorianamouroux** [gusbueno/github-organizations-page#1]
Hi!

After installing the dependencies, and setting my personal token in `.env` I run the app using `yarn start`. I get a blank page with the following error:

<img width="524" alt="Screenshot 2020-07-14 at 10 15 27" src="https://user-images.githubusercontent.com/13302836/87402207-82aaa880-c5bb-11ea-8342-6b4b55049727.png">

I'm using the latest version of Chrome

**Comment by gusbueno** [comment]
Hi @dorianamouroux!

The crash is due this line `(window as any).__REDUX_DEVTOOLS_EXTENSION__ && (window as any).__REDUX_DEVTOOLS_EXTENSION__()` in the `index.ts` file.

If you have no installed [REDUX DEV TOOL EXTENSION](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) in Chrome is gonna through this error. Sorry because I forgot this thing, I've already fixed and pushed the fix in `develop`, `master` and I created a new release `v1.0.4`

Thank you! ^^

**Comment by dorianamouroux** [comment]
Thanks Gustavo! It works now 👍
